### ISSUE TITLE
How about executable?

### ISSUE THREAD

**Issue by bogem** [gazay/ids_please#11]
Do you think about executable for this? It will be very convenient to grab and view all information from terminal window.
P.S. I can help with this and contribute if you interested in it

**Comment by gazay** [comment]
It would be great! =) Waiting for you PR then

**Comment by bogem** [comment]
👍
Will be after a while

**Comment by bogem** [comment]
Soon😉
![2015-08-19 10 36 11](https://cloud.githubusercontent.com/assets/13235519/9349342/45b662ac-465e-11e5-8cb7-9ebbb993ac16.png)
